version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1522481244
layout:
  navigation: {  }
  /header/: {  }
  /intro/:
    -
      - owlcarousel-1007
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-1605
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-1007:
    title: 'Owl Carousel'
    attributes:
      enabled: 0
      nav: enable
      autoplay: enable
      autoplaySpeed: '4000'
      items:
        -
          image: 'gantry-media://intro/000.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: '1'
        -
          image: 'gantry-media://intro/001.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: '2'
        -
          image: 'gantry-media://intro/002.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: '3'
        -
          image: 'gantry-media://intro/003.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: '4'
        -
          image: 'gantry-media://intro/004.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: '5'
        -
          image: 'gantry-media://intro/005.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: '6'
        -
          image: 'gantry-media://intro/006.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: '7'
