preset: preset5
accent:
  color-1: '#132d85'
navigation:
  background: '#424242'
  text-color: '#ffffff'
header:
  background: '#242424'
  background-image: 'gantry-media://header/AirbagUA_logo.png'
  background-overlay: disabled
