name: '10'
timestamp: 1554756585
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1522481244
positions:
  search: 'Module Position'
  callback: 'Заказать консультацию'
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-9312: 'System Messages'
  date:
    date-4940: Date
  custom:
    custom-3384: 'Custom HTML'
    custom-2496: 'Custom HTML'
    custom-5807: Intro
    custom-2652: 'Custom HTML'
    custom-8838: 'Custom HTML'
  social:
    social-3146: Social
  logo:
    logo-8580: 'Logo / Image'
    logo-2265: 'Logo / Image'
    logo-3805: 'Logo / Image'
  position:
    position-position-9001: 'Module Position'
    position-position-2749: 'Заказать консультацию'
  spacer:
    spacer-4293: Spacer
    spacer-2395: Spacer
  menu:
    menu-7734: Menu
  owlcarousel:
    owlcarousel-1007: 'Owl Carousel'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  content:
    system-content-1605: 'Page Content'
  copyright:
    copyright-5840: Copyright
  horizontalmenu:
    horizontalmenu-9708: 'Horizontal Menu'
  totop:
    totop-9210: 'To Top'
  mobile-menu:
    mobile-menu-4863: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-9312: system-messages-7972
    date-4940: date-6625
    custom-3384: custom-9435
    social-3146: social-3171
    logo-8580: logo-9608
    custom-2496: custom-9307
    position-position-9001: position-position-7102
    spacer-4293: spacer-9274
    menu-7734: menu-3134
    spacer-2395: spacer-3896
    footer: footer
    logo-3805: logo-9571
    copyright-5840: copyright-1736
    custom-8838: custom-9674
    horizontalmenu-9708: horizontalmenu-9034
    totop-9210: totop-8670
    offcanvas: offcanvas
    mobile-menu-4863: mobile-menu-5697
